hydra:
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

model:
  _target_: utils.model.FLOW
  c_dim: 128

device: cuda:0

training:
  batch_size: 64
  epochs: 300

test:
  num_steps: 10
  visualize: true
  vis_every_epoch: 10
  vis_count: 10

data:
  num_points: 2048
  gaussian_noise: 0.01
  unseen: false
  factor: 4
  num_workers: 8
  
optimizer:
  name: sgd
  lr: 1e-3
  weight_decay: 1e-5
  momentum: true
  nesterov: false
  use_scheduler: true
  scheduler: false
