defaults:
  - _self_
  - model: dcp
  - optim: sgd
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

model_name: ${hydra:runtime.choices.model}

hydra:
  run:
    dir: runs/${data.name}/${now:%Y-%m-%d}/${model_name}_${now:%Y-%m-%d-%H-%M-%S}/
  sweep:
    dir: runs/${data.name}/${now:%Y-%m-%d}
    subdir: ${model_name}_${now:%H-%M-%S}_${hydra.job.num}_${hydra.job.override_dirname}

device: cuda:0

training:
  batch_size: 32
  epochs: 250
  
data:
  name: modelnet40
  bunny_path: data/bunny/reconstruction/bun_zipper.ply
  num_points: 1024
  gaussian_noise: 0.0
  unseen: false
  factor: 4
  num_workers: 8
  partial_overlap: False
  keep_ratio: 1.0
  distance_range: 0.5

loss:
  _target_: utils.loss.ELBOObjective
  beta: 0.1

prune:
  ratio: 0.5