hydra:
  run:
    dir: runs/${data.dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model:
  _target_: utils.model.ProbabilisticGravityModel
  pooling: max
device: cuda:0

training:
  batch_size: 32
  epochs: 300

test:
  num_steps: 10
  visualize: true
  vis_every_epoch: 10
  vis_count: 10

data:
  dataset_name: bunny
  bunny_path: data/bunny/reconstruction/bun_zipper.ply
  num_points: 1024
  gaussian_noise: 0.01
  unseen: false
  factor: 4
  num_workers: 8
  
loss:
  _target_: utils.loss.VMFLoss

optimizer:
  name: sgd
  lr: 1e-3
  weight_decay: 1e-5
  momentum: true
  nesterov: false
  use_scheduler: true
  scheduler: false
