defaults:
  - _self_
  - model: flow_model
  - optim: sgd
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

model_name: ${hydra:runtime.choices.model}

hydra:
  run:
    dir: runs/${data.name}/${now:%Y-%m-%d}/${model_name}_${now:%Y-%m-%d-%H-%M-%S}/
  sweep:
    dir: runs/${data.name}/${now:%Y-%m-%d}
    subdir: ${model_name}_${now:%H-%M-%S}_${hydra.job.num}_${hydra.job.override_dirname}

device: cuda:0

training:
  batch_size: 32
  epochs: 100
  
test:
  num_steps: 10
  visualize: true
  vis_every_epoch: 10
  vis_count: 10

data:
  name: modelnet40
  bunny_path: data/bunny/reconstruction/bun_zipper.ply
  num_points: 1024
  gaussian_noise: 0.01
  unseen: false
  factor: 4
  num_workers: 8
  partial_overlap: True
  keep_ratio: 0.8
  path_generator:
    _target_: utils.path.SE3GeodesicProbPath
    manifold: 
      _target_: utils.se3.SE3

loss:
  _target_: utils.loss.ELBOObjective
  alpha: 1.0
  beta: 1.0